# Script to automatically fix migrations generated by `supabase db pull`
# Makes DROP POLICY and CREATE POLICY statements safe by adding conditional checks

param(
    [Parameter(Mandatory=$true)]
    [string]$MigrationFile
)

if (-not (Test-Path $MigrationFile)) {
    Write-Host "Error: Migration file not found: $MigrationFile" -ForegroundColor Red
    exit 1
}

Write-Host "Fixing migration: $MigrationFile" -ForegroundColor Yellow

$lines = Get-Content $MigrationFile
$output = @()
$inCreatePolicy = $false
$createPolicyLines = @()
$currentTable = $null
$dropPolicies = @{}  # table_name -> array of policy names

$i = 0
while ($i -lt $lines.Count) {
    $line = $lines[$i]
    
    # Check if helper function already exists
    if ($line -match "CREATE OR REPLACE FUNCTION drop_policies_if_table_exists") {
        # Helper function already exists, skip adding it
        $output += $line
        $i++
        continue
    }
    
    # Detect DROP POLICY statements
    if ($line -match 'drop policy\s+"([^"]+)"\s+on\s+"public"\."([^"]+)";' -or 
        $line -match 'DROP POLICY\s+"([^"]+)"\s+ON\s+"public"\."([^"]+)";') {
        $policyName = if ($matches[1]) { $matches[1] } else { $matches[1] }
        $tableName = if ($matches[2]) { $matches[2] } else { $matches[2] }
        
        if (-not $dropPolicies.ContainsKey($tableName)) {
            $dropPolicies[$tableName] = @()
        }
        if ($dropPolicies[$tableName] -notcontains $policyName) {
            $dropPolicies[$tableName] += $policyName
        }
        
        # Skip the original DROP POLICY line
        $i++
        continue
    }
    
    # Detect start of CREATE POLICY block
    if ($line -match 'create policy\s+"([^"]+)"\s+on\s+"public"\."([^"]+)"' -or
        $line -match 'CREATE POLICY\s+"([^"]+)"\s+ON\s+"public"\."([^"]+)"') {
        $currentTable = if ($matches[2]) { $matches[2] } else { $matches[2] }
        
        # If we have DROP policies for this table, add helper call first
        if ($dropPolicies.ContainsKey($currentTable) -and $dropPolicies[$currentTable].Count -gt 0) {
            $policiesArray = "'" + ($dropPolicies[$currentTable] -join "', '") + "'"
            $output += "-- Drop $currentTable policies only if table exists"
            $output += "SELECT drop_policies_if_table_exists('$currentTable', ARRAY[$policiesArray]);"
            $output += ""
            # Mark as processed
            $dropPolicies.Remove($currentTable)
        }
        
        # Start collecting CREATE POLICY lines
        $inCreatePolicy = $true
        $createPolicyLines = @($line)
        $i++
        continue
    }
    
    # Collect CREATE POLICY block lines
    if ($inCreatePolicy) {
        $createPolicyLines += $line
        
        # Check if this is the end of the CREATE POLICY statement
        if ($line -match ';' -and $line.Trim() -match ';$') {
            # End of CREATE POLICY - wrap it
            $policyBlock = $createPolicyLines -join "`n"
            
            # Extract policy details for EXECUTE statement
            $policyBlockEscaped = $policyBlock -replace "'", "''"
            
            # Wrap in DO block
            $output += "-- Create $currentTable policies only if table exists"
            $output += "DO `$`$"
            $output += "BEGIN"
            $output += "  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = '$currentTable') THEN"
            $output += "    EXECUTE '$policyBlockEscaped';"
            $output += "  END IF;"
            $output += "END `$`$;"
            $output += ""
            
            $inCreatePolicy = $false
            $createPolicyLines = @()
            $currentTable = $null
        }
        $i++
        continue
    }
    
    # Regular line - add as is
    $output += $line
    $i++
}

# Add helper function at the beginning if we used it
if ($output -join "`n" -match "drop_policies_if_table_exists" -and 
    ($output -join "`n") -notmatch "CREATE OR REPLACE FUNCTION drop_policies_if_table_exists") {
    $helperFunction = @"
-- Helper function to safely drop policies if table exists
CREATE OR REPLACE FUNCTION drop_policies_if_table_exists(
  table_name text,
  policy_names text[]
) RETURNS void AS `$$
DECLARE
  policy_name text;
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables 
             WHERE table_schema = 'public' 
             AND information_schema.tables.table_name = drop_policies_if_table_exists.table_name) THEN
    FOREACH policy_name IN ARRAY policy_names
    LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_name, drop_policies_if_table_exists.table_name);
    END LOOP;
  END IF;
END;
`$$ LANGUAGE plpgsql;

"@
    $output = $helperFunction.Split("`n") + $output
}

# Write the fixed content
$output -join "`n" | Set-Content -Path $MigrationFile

Write-Host "Migration fixed successfully!" -ForegroundColor Green
Write-Host "Please review the changes before committing." -ForegroundColor Yellow
